# Generated by Django 5.1.7 on 2025-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "registro_ans",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("cnpj", models.BigIntegerField()),
                ("razao_social", models.CharField(max_length=255)),
                ("nome_fantasia", models.CharField(max_length=255, null=True)),
                ("modalidade", models.CharField(max_length=100, null=True)),
                ("logradouro", models.CharField(max_length=255, null=True)),
                ("numero", models.CharField(max_length=50, null=True)),
                ("complemento", models.CharField(max_length=255, null=True)),
                ("bairro", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("uf", models.CharField(max_length=2, null=True)),
                ("cep", models.BigIntegerField(null=True)),
                ("ddd", models.SmallIntegerField()),
                ("telefone", models.BigIntegerField(null=True)),
                ("fax", models.BigIntegerField(null=True)),
                ("endereco_eletronico", models.CharField(max_length=255, null=True)),
                ("representante", models.CharField(max_length=255, null=True)),
                ("cargo_representante", models.CharField(max_length=255, null=True)),
                ("regiao_de_comercializacao", models.IntegerField(null=True)),
                ("data_registro_ans", models.DateField(null=True)),
            ],
        ),
    ]
