# Generated by Django 5.1.7 on 2025-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="ddd",
            field=models.SmallIntegerField(null=True),
        ),
    ]
