CREATE TABLE contabilidade_2024 (
    DATA DATE,
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL NUMERIC,
    VL_SALDO_FINAL NUMERIC,
    PRIMARY KEY (DATA, REG_ANS, CD_CONTA_CONTABIL)
);

--- Criar tabela temporária para importação dos dados

CREATE TABLE contabilidade_2024_tmp (
    DATA DATE,
    REG_ANS INT,
    CD_CONTA_CONTABIL INT,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL TEXT,
    VL_SALDO_FINAL TEXT,
    PRIMARY KEY (DATA, REG_ANS, CD_CONTA_CONTABIL)
);