INSERT INTO contabilidade_2024 (DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT 
    DATA,
    REG_ANS,
    CD_CONTA_CONTABIL,
    DESCRICAO,
    CAST(REPLACE(VL_SALDO_INICIAL, ',', '.') AS NUMERIC),
    CAST(REPLACE(VL_SALDO_FINAL, ',', '.') AS NUMERIC)
FROM contabilidade_2024_tmp;

INSERT INTO contabilidade_2023 (DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT 
    DATA,
    REG_ANS,
    CD_CONTA_CONTABIL,
    DESCRICAO,
    CAST(REPLACE(VL_SALDO_INICIAL, ',', '.') AS NUMERIC),
    CAST(REPLACE(VL_SALDO_FINAL, ',', '.') AS NUMERIC)
FROM contabilidade_2023_tmp;

-- Faz a conversão dos dados das colunas VL_SALDO_INICIAL e VL_SALDO_FINAL